name: CI_Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Получение исходного кода
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.12"

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Сборка проекта (проверка импорта)
      - name: Build project
        run: |
          python -m compileall app

      # 5. Запуск модульных тестов
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v
