name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Получение кода
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. Сборка проекта
      - name: Build project
        run: |
          python -m compileall app

      # 5. Запуск тестов (CI)
      - name: Run tests
        run: |
          python -m pytest -v

      # 6. Подготовка артефакта (Docker image)
      - name: Build Docker image
        run: |
          docker build -t pr3-test-image .

      # 7. Деплой в test среду
      - name: Run container (Test environment)
        run: |
          docker run -d --name pr3-test-container pr3-test-image

      # 8. Проверка запуска
      - name: Check container status
        run: |
          docker ps